version: 2
updates:
- package-ecosystem: pip
  directory: "/code-env/python/spec"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: deskew
    versions:
    - 0.10.10
    - 0.10.12
    - 0.10.13
    - 0.10.16
    - 0.10.19
    - 0.10.25
    - 0.10.26
    - 0.10.27
    - 0.10.3
    - 0.10.5
    - 0.10.6
    - 0.10.8
    - 0.10.9
  - dependency-name: matplotlib
    versions:
    - 3.3.4
    - 3.4.0
  - dependency-name: pillow
    versions:
    - 8.1.0
    - 8.1.1
    - 8.1.2
  - dependency-name: opencv-python
    versions:
    - 4.5.1.48
  - dependency-name: pdf2image
    versions:
    - 1.14.0
  - dependency-name: pytesseract
    versions:
    - 0.3.7
